controller_list:
  - name: fake_manipulator_controller
    joints:
      - dorna_base_to_dorna_arm_0
      - dorna_arm_0_to_dorna_arm_1
      - dorna_arm_1_to_dorna_arm_2
      - dorna_arm_2_to_dorna_arm_3
      - dorna_arm_3_to_dorna_arm_4