dorna:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController #joint_trajectory_controller/JointTrajectoryController #
    publish_rate: 50

  # For Gazebo+MoveIt (EFFORT CONTROLLER)
  dorna_effort_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - dorna_base_to_dorna_arm_0
      - dorna_arm_0_to_dorna_arm_1
      - dorna_arm_1_to_dorna_arm_2
      - dorna_arm_2_to_dorna_arm_3
      - dorna_arm_3_to_dorna_arm_4
    gains: # Required because we're controlling an effort interface
      dorna_base_to_dorna_arm_0: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 0.01}
      dorna_arm_0_to_dorna_arm_1: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 0.01}
      dorna_arm_1_to_dorna_arm_2: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 0.01}
      dorna_arm_2_to_dorna_arm_3: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 0.01}
      dorna_arm_3_to_dorna_arm_4: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 0.01}
    # allow_partial_joints_goal: true
    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      dorna_base_to_dorna_arm_0: {trajectory: 0.0, goal: 0.0}
      dorna_arm_0_to_dorna_arm_1: {trajectory: 0.0, goal: 0.0}
      dorna_arm_1_to_dorna_arm_2: {trajectory: 0.0, goal: 0.0}
      dorna_arm_2_to_dorna_arm_3: {trajectory: 0.0, goal: 0.0}
      dorna_arm_3_to_dorna_arm_4: {trajectory: 0.0, goal: 0.0}
    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10

  # For Gazebo+MoveIt (POSITION CONTROLLER)
  dorna_position_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - dorna_base_to_dorna_arm_0
      - dorna_arm_0_to_dorna_arm_1
      - dorna_arm_1_to_dorna_arm_2
      - dorna_arm_2_to_dorna_arm_3
      - dorna_arm_3_to_dorna_arm_4
    gains: 
      dorna_base_to_dorna_arm_0: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 0.01}
      dorna_arm_0_to_dorna_arm_1: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 0.01}
      dorna_arm_1_to_dorna_arm_2: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 0.01}
      dorna_arm_2_to_dorna_arm_3: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 0.01}
      dorna_arm_3_to_dorna_arm_4: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 0.01}
    allow_partial_joints_goal: true
    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      dorna_base_to_dorna_arm_0: {trajectory: 0.0, goal: 0.0}
      dorna_arm_0_to_dorna_arm_1: {trajectory: 0.0, goal: 0.0}
      dorna_arm_1_to_dorna_arm_2: {trajectory: 0.0, goal: 0.0}
      dorna_arm_2_to_dorna_arm_3: {trajectory: 0.0, goal: 0.0}
      dorna_arm_3_to_dorna_arm_4: {trajectory: 0.0, goal: 0.0}
    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10
  
  #Needed for position_controllers/JointTrajectoryController
  gazebo_ros_control:
    pid_gains:
      dorna_base_to_dorna_arm_0:  {p: 100.0, i: 0.01, d: 10.0}
      dorna_arm_0_to_dorna_arm_1: {p: 100.0, i: 0.01, d: 10.0}
      dorna_arm_1_to_dorna_arm_2: {p: 100.0, i: 0.01, d: 10.0}
      dorna_arm_2_to_dorna_arm_3: {p: 100.0, i: 0.01, d: 10.0}
      dorna_arm_3_to_dorna_arm_4: {p: 100.0, i: 0.01, d: 10.0}

  #For DEBUGGING Gazebo_ros_control
  joint0_position_controller:
    type: effort_controllers/JointPositionController #position_controllers/JointPositionController
    joint: dorna_base_to_dorna_arm_0
    pid: {p: 1.0, i: 0, d: 0}
  joint1_position_controller:
    type: effort_controllers/JointPositionController #position_controllers/JointPositionController
    joint: dorna_arm_0_to_dorna_arm_1
    pid: {p: 1.0, i: 0, d: 0}
  joint2_position_controller:
    type: effort_controllers/JointPositionController #position_controllers/JointPositionController
    joint: dorna_arm_1_to_dorna_arm_2
    pid: {p: 1.0, i: 0, d: 0}
  joint3_position_controller:
    type: effort_controllers/JointPositionController #position_controllers/JointPositionController
    joint: dorna_arm_2_to_dorna_arm_3
    pid: {p: 1.0, i: 0, d: 0}
  joint4_position_controller:
    type: effort_controllers/JointPositionController #position_controllers/JointPositionController
    joint: dorna_arm_3_to_dorna_arm_4
    pid: {p: 1.0, i: 0, d: 0}
